import express from "express";
import { deleteAccount, forgetPassword, getAccount, getAllAccount, login, register, resendOTP, searchAccount, update, updateForgetPassword, updatePassword, verifyForgetCode, verifyOTP } from "../controllers/userController.js";
import isAuth from "../middlewares/auth.js";
import singleUpload from "../middlewares/singleUpload.js";
import isAdmin from "../middlewares/admin.js";
export const userRouter=express.Router();
userRouter.post("/register",register);
userRouter.post("/verify-email",verifyOTP);
userRouter.post("/otp-resend",resendOTP);
userRouter.post("/login",login);
userRouter.put("/update",isAuth,singleUpload,update);
userRouter.put("/update-password",isAuth,updatePassword);
userRouter.put("/forget-password",forgetPassword);
userRouter.put("/forget-password-verification",verifyForgetCode);
userRouter.put("/forget-password-update",updateForgetPassword);
userRouter.delete("/delete-account/:id",isAuth,isAdmin,deleteAccount);
userRouter.get("/get-account/:id",isAuth,isAdmin,getAccount);
userRouter.get("/get-all-account",isAuth,isAdmin,getAllAccount);
userRouter.get("/search-account/:search_str",isAuth,isAdmin,searchAccount);